/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://5f6fes6sjzecvdrltidnywl564.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-w2vavkwyananbdudenas52iemu",
    "aws_cognito_identity_pool_id": "us-west-1:b4cf4e4a-d13f-48fe-afb3-21fa3db92e90",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_nAVRicUTV",
    "aws_user_pools_web_client_id": "5cpbc160culgduhmrdlkmbf8k2",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "cathartic-network-next-storage-016f545c184217-staging",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;
